version: "3.9"
services:
  ryu-controller:
    build: ./Ryu-Docker/
    ports: 
      - "6633:6633"
    
    working_dir: "/root/ryu/"
    tty: true
    #entrypoint: "ryu-manager ./WAMS-Resilience-App/1_redundant_path_sflow.py --observe-links"
    entrypoint: "ryu-manager ./WAMS-Resilience-App/qos.py --observe-links"
    restart: always
    volumes:
      - /home/sgsdn/workspace/controller/src:/root/ryu/WAMS-Resilience-App
    network_mode: host
